### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by AfrahAsif** [CristiVlad25/py-scripts-other#1]
I tried the following code from your repo,

**import boto3
from pygame import mixer
import os
polly = boto3.client('polly')
spoken_text = polly.synthesize_speech(Text='I am Emma. You know me from Ivona.',OutputFormat='mp3',VoiceId='Emma')
with open('output.mp3', 'wb') as f:
    f.write(spoken_text['AudioStream'].read())
    f.close()

mixer.init()
mixer.music.load('output.mp3')
mixer.music.play()
while mixer.music.get_busy() == True:
    pass
mixer.quit()
os.remove('output.mp3')**

but on running it shows an error [on os.remove('output.mp3') ] saying,
**PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'output1.mp3**

Can I please know what mistake am I doing?

**Comment by CristiVlad25** [comment]
It's an issue coming from pygame and the way it handles the output being saved to file. I wasnt able to figure it out, unfortunately. And since this was a temporary project, I didn't spend too much time trying to get to a resolution.

**Comment by ghanatheyakash** [comment]
File "D:\new.py", line 6, in <module>
    instance = vr(api_key='npfXBlXhvffim3eXjXtMvBWZQL2Si7fbGS02tc_6l7nz', version='2016-05-20')

  File "C:\Users\akash\anaconda3\lib\site-packages\watson_developer_cloud\utils.py", line 10, in deprecated_func
    return func(*args, **kwargs)

TypeError: __init__() got an unexpected keyword argument 'api_key'

**Comment by ghanatheyakash** [comment]
from watson_developer_cloud import VisualRecognitionV3 as vr

# creating a VR instance

instance = vr(api_key='npfXBlXhvffim3eXjXtMvBWZQL2Si7fbGS02tc_6l7nz', version='2016-05-20')

# select an image (local or url). Copy its location (path or url):

img = instance.classify(images_url='https://i2.wp.com/ceklog.kindel.com/wp-content/uploads/2013/02/firefox_2018-07-10_07-50-11.png?fit=641%2C618&ssl=1')

# you can run this code in the interpreter. If you request >>> img it will output a json formatted result
# getting down the json tree with the following input will display what Watson sees in the image, and the confidence level

# >>> img['images'][0]['classifiers'][0]['classes']

# for a better view of the results, you can use pprint
import pprint
pprint.pprint(img['images'][0]['classifiers'][0]['classes'])

**Comment by CristiVlad25** [comment]
Closing this as non applicable anymore
